#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 21, 2017 12:34:15 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import editor_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    editor_support.set_Tk_var()
    top = Wirespace_Editor (root)
    editor_support.init(root, top)
    root.mainloop()

w = None
def create_Wirespace_Editor(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    editor_support.set_Tk_var()
    top = Wirespace_Editor (w)
    editor_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Wirespace_Editor():
    global w
    w.destroy()
    w = None


class Wirespace_Editor:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font11 = "-family Ubuntu -size 10 -weight bold -slant roman "  \
            "-underline 0 -overstrike 0"
        font12 = "-family Ubuntu -size 10 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("594x450+465+181")
        top.title("Wirespace - Editor")



        self.Frame1 = Frame(top)
        self.Frame1.place(relx=0.01, rely=0.02, relheight=0.89, relwidth=0.97)
        self.Frame1.configure(relief=SUNKEN)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=SUNKEN)
        self.Frame1.configure(width=577)

        self.Link = Entry(self.Frame1)
        self.Link.place(relx=0.02, rely=0.02, relheight=0.07, relwidth=0.69)
        self.Link.configure(background="white")
        self.Link.configure(font="TkFixedFont")
        self.Link.configure(width=396)

        self.Connect = Button(self.Frame1)
        self.Connect.place(relx=0.71, rely=0.02, height=30, width=157)
        self.Connect.configure(activebackground="#d9d9d9")
        self.Connect.configure(text='''Connect''')
        self.Connect.configure(width=157)

        self.FolderContainer = Listbox(self.Frame1)
        self.FolderContainer.place(relx=0.02, rely=0.25, relheight=0.62
                , relwidth=0.48)
        self.FolderContainer.configure(background="#c8c8c8")
        self.FolderContainer.configure(font="TkFixedFont")
        self.FolderContainer.configure(selectbackground="#004bff")
        self.FolderContainer.configure(selectmode=SINGLE)
        self.FolderContainer.configure(width=275)
        self.FolderContainer.configure(listvariable=editor_support.file_data)

        self.Edit = Button(self.Frame1)
        self.Edit.place(relx=0.02, rely=0.9, height=30, width=275)
        self.Edit.configure(activebackground="#d9d9d9")
        self.Edit.configure(text='''Edit locally''')
        self.Edit.configure(width=273)

        self.Save = Button(self.Frame1)
        self.Save.place(relx=0.5, rely=0.9, height=30, width=275)
        self.Save.configure(activebackground="#d9d9d9")
        self.Save.configure(text='''Save remotely''')

        self.PathBox = Message(self.Frame1)
        self.PathBox.place(relx=0.19, rely=0.12, relheight=0.05, relwidth=0.79)
        self.PathBox.configure(highlightcolor="#ffffff")
        self.PathBox.configure(text='''Message''')
        self.PathBox.configure(textvariable=editor_support.current_path)
        self.PathBox.configure(width=457)

        self.Message3 = Message(self.Frame1)
        self.Message3.place(relx=0.02, rely=0.12, relheight=0.05, relwidth=0.17)
        self.Message3.configure(font=font11)
        self.Message3.configure(text='''Current path''')
        self.Message3.configure(width=83)

        self.FileContainer = Listbox(self.Frame1)
        self.FileContainer.place(relx=0.5, rely=0.25, relheight=0.62
                , relwidth=0.48)
        self.FileContainer.configure(background="#c8c8c8")
        self.FileContainer.configure(font="TkFixedFont")
        self.FileContainer.configure(selectbackground="#004bff")
        self.FileContainer.configure(selectmode=SINGLE)
        self.FileContainer.configure(width=275)

        self.Message4 = Message(self.Frame1)
        self.Message4.place(relx=0.02, rely=0.2, relheight=0.05, relwidth=0.48)
        self.Message4.configure(font=font12)
        self.Message4.configure(text='''Directories''')
        self.Message4.configure(width=270)

        self.Message5 = Message(self.Frame1)
        self.Message5.place(relx=0.5, rely=0.2, relheight=0.05, relwidth=0.48)
        self.Message5.configure(font=font12)
        self.Message5.configure(text='''Files''')
        self.Message5.configure(width=268)

        self.StatusBox = Message(top)
        self.StatusBox.place(relx=0.01, rely=0.93, relheight=0.04, relwidth=0.97)

        self.StatusBox.configure(text='''Message''')
        self.StatusBox.configure(textvariable=editor_support.status)
        self.StatusBox.configure(width=573)






if __name__ == '__main__':
    vp_start_gui()



