# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='path_shared',
            field=models.TextField(default='/home/yash/Public'),
        ),
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(default=share.models.gen_key, max_length=32, primary_key=True, serialize=False),
        ),
    ]
