# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20171003_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(default=share.models.gen_key, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
