# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import share.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key', models.CharField(default=share.models.gen_key, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('r', 'Read-only'), ('w', 'Read-and-Write')], default='r', max_length=1)),
                ('username', models.CharField(default='Anonymous', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('space_shared', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(default=None)),
            ],
        ),
    ]
