# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import share.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key', models.CharField(default=share.models.gen_key, editable=False, help_text='This value is temporary. Use the final value after saving.', max_length=16, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('r', 'Read-only'), ('w', 'Read-and-Write')], default='r', max_length=1)),
                ('shared_to', models.CharField(default='Anonymous', max_length=30)),
                ('email', models.EmailField(help_text='E-mail of the person with whom the space is shared', max_length=254)),
                ('space_allotted', models.BigIntegerField(help_text='Space you want to share in BYTES')),
                ('path_shared', models.TextField(default='/home/yash/Public', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token', models.CharField(default=share.models.gen_token, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('ip', models.CharField(default=None, max_length=15)),
                ('link', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='share.Key')),
            ],
        ),
    ]
