# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='link',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='share.Key'),
        ),
    ]
