# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import share.models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20171010_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key',
            field=models.CharField(default=share.models.gen_key, editable=False, help_text='This value is temporary. Use the final value after saving.', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=share.models.gen_token, editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
