# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20171003_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='path_shared',
            field=models.TextField(default='/home/yash/Public', max_length=100),
        ),
    ]
