# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20171010_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='email',
            field=models.EmailField(help_text='E-mail of the person with whom the space is shared', max_length=254, null=True),
        ),
    ]
