# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 12:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20171010_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 18, 12, 53, 40, 331121, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='key',
            name='path_shared',
            field=models.TextField(default='/home/yash', max_length=100),
        ),
    ]
