# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_auto_20171019_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 6, 6, 21, 297810, tzinfo=utc), editable=False),
        ),
    ]
