# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0010_auto_20171019_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
