# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0011_auto_20171019_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='ip',
            new_name='IP',
        ),
        migrations.AlterField(
            model_name='key',
            name='path_shared',
            field=models.TextField(default='/home/yash/Desktop', max_length=100),
        ),
        migrations.AlterField(
            model_name='key',
            name='space_allotted',
            field=models.BigIntegerField(default=4096, help_text='Space to be shared, in BYTES'),
        ),
    ]
